In [2]:
import numpy as np 

A = 1-(3/8*(-1/3 *(np.log2(1/3))-2/3*(np.log2(2/3))) + 5/8*(-3/5*(np.log2(3/5))-2/5*(np.log2(2/5))))
B = 1-(3/8*(-1/3 *(np.log2(1/3))-2/3*(np.log2(2/3))) + 3/8*(-1/3*(np.log2(1/3))-2/3*(np.log2(2/3))))
C = 1- 5/8*(-4/5*(np.log2(4/5))-1/5*(np.log2(1/5)))
print(A)
print(B)
print(C)

0.04879494069539847
0.31127812445913283
0.5487949406953986


In [3]:
D1 = -(1/5*np.log2(1/5)+4/5*np.log2(4/5))

D1_A = D1 - 2/5*(-1/2*np.log2(1/2)-1/2*np.log2(1/2))
D1_B = D1 - 3/5*(-1/3*np.log2(1/3)-2/3*np.log2(2/3))

print(D1_A)
print(D1_B)

0.3219280948873623
0.17095059445466865


In [1]:
import numpy as np 


In [7]:
labels = [1,1,0,0,0,0,1,0,0,0]
labels = np.array(labels)
print(labels)
unique_lbls = np.unique(labels)
print(unique_lbls)

[1 1 0 0 0 0 1 0 0 0]
[0 1]


In [10]:
entropy = 0
for lbl in unique_lbls:
    percentage = len(np.extract(labels == lbl, labels))/len(labels)
    print(percentage)
    entropy -= percentage * np.log2(percentage)

print(entropy)

0.7
0.3
0.8812908992306927


In [11]:
cls = int(np.sum(labels == 1) >= np.sum(labels == 0))
print(cls)

0


In [12]:
a = np.sum(np.abs(cls - labels)) / np.prod(np.size(labels))
print(a)

0.3


In [3]:
import numpy as np

X = [[1,2,3],[1,1,1],[2,3,3]]
X = np.array(X)
print(X)

print(np.unique(X))

[[1 2 3]
 [1 1 1]
 [2 3 3]]
[1 2 3]


In [1]:
import re 
import numpy as np 

file = "education_train.tsv"
with open(file, "r") as f:
    data  = []
    lines = f.readlines()
    for idx, line in enumerate(lines):
        features = re.split("[\n\t]", line)[:-1]

        if idx == 0:
            labels = features
        else:
            features = [int(feature) for feature in features]
            data.append(features)
    my_data = np.array(data)



In [4]:
headers = np.array(labels)
print(headers[:-1])


['M1' 'M2' 'M3' 'M4' 'M5' 'P1' 'P2' 'P3' 'P4' 'F']


In [11]:
import numpy as np 
feature = np.array([1,1,1,0,0,1,1,1,0,1])
print(feature)
unique_vals = np.unique(feature)
print(unique_vals)
for val in unique_vals:
    val_mask = feature == val 
    print(val_mask)
    print(len(np.extract(val_mask, feature)))
    print([val_mask.ravel()])

[1 1 1 0 0 1 1 1 0 1]
[0 1]
[False False False  True  True False False False  True False]
3
[array([False, False, False,  True,  True, False, False, False,  True,
       False])]
[ True  True  True False False  True  True  True False  True]
7
[array([ True,  True,  True, False, False,  True,  True,  True, False,
        True])]


In [4]:
import torch 
y = torch.tensor([[1,2],[3,4]])
a = torch.tile(y, (2,1))
print(a)

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


In [1]:
import numpy as np
scores = np.array([90, 0, 75, 0, 82, 95, 0])
zero_scores = scores[scores == 0]

print("分数为0的学生: ", zero_scores)


分数为0的学生的index:  [0 0 0]


In [26]:
import numpy as np

hdrs =np.array(['a', 'b', 'c'])
attr = 'b'
if attr not in hdrs:
    print("not a attribution")

data = np.array([[1, 0, 0],[0, 1, 1],[1, 0, 1]])
idx = attr == hdrs
# print(idx)   [False True False]
feature = data[:, idx]
print(feature.shape)
print(feature)

unique_vals = np.unique(feature)
for val in unique_vals:
    val_mask = feature == val
    print(val_mask)
    print(np.extract(val_mask, feature)) # 其实这里就相当于是np.extract(feature==val, feature)
    break


print(val_mask.ravel())
lbls = np.array([1,0,0])
print(lbls[val_mask.ravel()])



(3, 1)
[[0]
 [1]
 [0]]
[[ True]
 [False]
 [ True]]
[0 0]
[ True False  True]
[1 0]


In [18]:
print(len(data))

2


Inspecting the Data 
inspection.py
计算the label entropy和error rate(用majority_vote_classifier计算出来的)\
$H(Y)=-\sum_{i=1}^2p_i\log p_i$



在decision_tree.py中，实现一个决策树学习器。此文件应该学习具有指定最大深度的决策树，以指定格式打印决策树，预测训练和测试阳历的标签，并计算训练和测试误差

depth=0就表示用Majority_vote_decision

depth不能超过属性值的总数目？
如果超出总属性值则按最大的属性值来构造决策树

画出来|||的图的含义是什么？到最后的话比如small depth=2 画出来的chest_pain=0, thalassemia=0:[4 0/12 1]说明，按照chest_pain和thelassemia分类并不纯，如果分类不纯则按少数服从多数，即这里4<12，所以y = 1


decision_tree.py里面的len(sys.argv) == 5:是什么含义？？？
表示程序化生成决策树，一次性可以生成指定的不同depth的决策树，根据train_data来生成对应的决策树，用生成的决策树再去对train,test进行分类并输出分类的结果，计算error(train), error(test)


decision_tree.py里面的len(sys.argv) == 4:是什么含义？？？
自动生成depth=[0,1,2...L]
L = num(attributions) + 1 # + 1 是为了测试如果depth超出属性的数目的话，会如何处理





In [3]:
depth=[]
if not depth:
    print("depth is None")
print(list(range(4)))

depth is None
[0, 1, 2, 3]
